name: Release

on:
  push:
    # branches:
    #   - main
    tags: ["v*.*.*"]
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      # build_linux:
      #   description: '构建 Linux (x64)'
      #   type: boolean
      #   default: true
      build_windows:
        description: '构建 Windows (x64)'
        type: boolean
        default: true
      # build_macos:
      #   description: '构建 macOS (Universal)'
      #   type: boolean
      #   default: true
      # build_android:
      #   description: '构建 Android (APK)'
      #   type: boolean
      #   default: true
      # build_ios:
      #   description: '构建 iOS (No Codesign)'
      #   type: boolean
      #   default: true
      # build_web:
      #   description: '构建 Web (standalone + embedded)'
      #   type: boolean
      #   default: true

jobs:
  build_platform:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x86
            files: |
              dist/

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml or .fvmrc or .fvm/fvm_config.json
          cache: true

      # - name: Setup Rust toolchain
      #   uses: dtolnay/rust-toolchain@stable
      #   with:
      #     toolchain: stable

      - name: Install Xcode
        if: ${{matrix.platform == 'ios'}}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: 📦 Install Dependencies
        run: flutter pub get

      - name: Install fastforge
        run: dart pub global activate fastforge

      - name: Build Windows ZIP
        run: fastforge package --platform windows --targets exe,zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: ${{matrix.platform}}-${{matrix.arch}}
          path: ${{matrix.files}}

  upload:
    runs-on: ubuntu-22.04
    needs:
      - build_platform
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: ./Release-Binaries

      - name: Install dependencies
        run: sudo apt-get install tree -y

      - name: Generate Checksums
        run: |
          tree .
          find Release-Binaries -type f -exec md5sum {} \; >> RELEASE.md5sum
          find Release-Binaries -type f -exec sha256sum {} \; >> RELEASE.sha256sum
          sed -i 's|Release-Binaries/.*/\([^/]*\)$|\1|' RELEASE.sha256sum RELEASE.md5sum
          sed -i 's|Release-Binaries/||' RELEASE.sha256sum RELEASE.md5sum

      - name: Extract pubspec version
        run: |
          echo "PUBSPEC_VERSION=$(grep -oP 'version:\s*\K[^+]+(?=\+)' pubspec.yaml)" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: sums
          path: |
            RELEASE.md5sum
            RELEASE.sha256sum

      - name: Upload Release Binaries (stable)
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.PUBSPEC_VERSION }} # mind the "v" prefix
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          allowUpdates: true
          artifacts: Release-Binaries/**/*,RELEASE.sha256sum,RELEASE.md5sum
